// This sample program is generated by ChatGPT.

// Function definitions
int add(int a, int b)
{
    return a + b;
}

int subtract(int a, int b)
{
    return a - b;
}

int multiply(int a, int b)
{
    return a * b;
}

int divide(int a, int b)
{
    return a / b;
}

int factorial(int n)
{
    int result = 1;
    for (int i = 1; i <= n; i++)
    {
        result *= i;
    }
    return result;
}

// Main function
int main()
{
    int num1, num2, choice, result;

    printf("Enter two integers: ");
    scanf("%d %d", &num1, &num2);

    printf("Choose an operation to perform:\n");
    printf("0. Exit\n");
    printf("1. Addition\n");
    printf("2. Subtraction\n");
    printf("3. Multiplication\n");
    printf("4. Division\n");
    printf("5. Factorial of the first number\n");
    printf("Enter your choice (1-5): ");
    scanf("%d", &choice);

    while (choice != 0)
    {
        if (choice == 1)
        {
            result = add(num1, num2);
            printf("Result: %d\n", result);
        }
        else if (choice == 2)
        {
            result = subtract(num1, num2);
            printf("Result: %d\n", result);
        }
        else if (choice == 3)
        {
            result = multiply(num1, num2);
            printf("Result: %d\n", result);
        }
        else if (choice == 4)
        {
            if (num2 != 0)
            {
                result = divide(num1, num2);
                printf("Result: %d\n", result);
            }
            else
            {
                printf("Error: Division by zero is not allowed.\n");
            }
        }
        else if (choice == 5)
        {
            result = factorial(num1);
            printf("Factorial of %d is: %d\n", num1, result);
        }
        else
        {
            printf("Invalid choice.\n");
        }
        scanf("%d", &choice);
    }
}
