// This sample program is generated by ChatGPT.

// Function to print numbers and demonstrate various loops
void printOddNumbers(int limit)
{
    printf("Using for-loop:\n");
    for (int i = 1; i <= limit; i++)
    {
        if (i % 2 == 0)
        {
            continue; // Skip even numbers
        }
        printf("%d ", i);
    }
    printf("\n");

    printf("Using while-loop:\n");
    int j = 1;
    while (j <= limit)
    {
        if (j % 2 == 0)
        {
            j++;
            continue; // Skip even numbers
        }
        printf("%d ");
        //         ^ Error: Variable is disappeared.
        j++;
    }
    printf("\n");

    printf("Using do-while-loop:\n");
    int k = 1;
    do
    {
        if (k % 2 == 0)
        {
            k++;
            continue; // Skip even numbers
        }
        printf("%d ", k);
        k++;
    } while (k <= limit);
    printf("\n");

    callAFunction();
    // ^ Error: call a nonexist function.
}

int main()
{
    // int limit;
    //  ^ Error: Comment the declaration.

    // Taking user input for limit
    printf("Enter a limit to print odd numbers below it: ");
    scanf("%d", &limit);

    // Function call to print numbers
    printOddNumbers(limit);
}
